set number                      " show current line number even in relative mode
filetype off
syntax enable

imap ;; <ESC>
imap jj <ESC>

call plug#begin('~/.vim/plugged')

" core editing
Plug 'tpope/vim-surround'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-ragtag'
Plug 'tomtom/tcomment_vim'
Plug 'raimondi/delimitmate'
Plug 'mg979/vim-visual-multi'

" navigation + search
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'christoomey/vim-tmux-navigator'
Plug 'roman/golden-ratio'

" display
Plug 'jeffkreeftmeijer/vim-numbertoggle'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'nanotech/jellybeans.vim'

" linting + completion
Plug 'dense-analysis/ale'
Plug 'neoclide/coc.nvim', { 'branch': 'release' }

" language support
Plug 'sheerun/vim-polyglot'
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }

" utilities
Plug 'godlygeek/tabular'
Plug 'dhruvasagar/vim-table-mode'
Plug 'aserebryakov/vim-todo-lists'

call plug#end()
filetype plugin indent on

set autoindent
set autoread
set backspace=2                 " fix broken backspace in some setups
set clipboard=unnamed           " yank and paste with system clipboard
set directory-=.                " don't store swapfiles in current directory
set expandtab                   " expand tabs to spaces
set ignorecase                  " case-insensitive search
set incsearch                   " search as you type
set laststatus=2                " always show statusline
set ruler                       " show where you are
set scrolloff=3                 " show context above/below cursorline
set shiftwidth=4                " normal mode indentation uses 4 spaces
set smartcase                   " case-sensitive search if any caps
set smartindent
set softtabstop=4               " insert mode tab and backspace use 4 spaces
set splitbelow
set splitright
set tabstop=8                   " actual tabs occupy 8 characters
set wildmode=longest:full
set wildchar=<Tab>
set wildmenu

" colored column at 80 chars
set colorcolumn=80

" colorscheme
set t_Co=256
colorscheme jellybeans

let g:VimTodoListsMoveItems = 0

" fix cursor in tmux
if exists('$TMUX')
  let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
  let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
else
  let &t_SI = "\<Esc>]50;CursorShape=1\x7"
  let &t_EI = "\<Esc>]50;CursorShape=0\x7"
endif

" mouse
set mouse=a

" ############################ keyboard shortcuts ############################

" vim splits — easier pane switching
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" correct :W to :w, :Q to :q, :Wq to :wq
cnoreabbrev <expr> W ((getcmdtype() is# ':' && getcmdline() is# 'W')?('w'):('W'))
cnoreabbrev <expr> Q ((getcmdtype() is# ':' && getcmdline() is# 'Q')?('q'):('Q'))
cnoreabbrev <expr> Wq ((getcmdtype() is# ':' && getcmdline() is# 'Wq')?('wq'):('Wq'))

let mapleader = ','

" strip trailing whitespace
nnoremap <leader>W :%s/\s\+$//<cr>:let @/=''<CR>

" fzf bindings
nnoremap <leader>f :Files<CR>
nnoremap <leader>b :Buffers<CR>
nnoremap <leader>r :Rg<CR>
nnoremap <leader>l :Lines<CR>

" ############################ filetype settings ############################

au BufNewFile,BufRead *.json.jbuilder set ft=ruby
au BufNewFile,BufRead *.ejs set ft=html

cnoremap %% <C-R>=expand('%:h').'/'<cr>

" text files
au BufNewFile,BufRead *.txt set tw=80 spell
au BufNewFile,BufRead *.md set tw=80 spell
au BufNewFile,BufRead *.tex set tw=80

" folding
au BufNewFile,BufRead *.py setlocal foldmethod=indent
au BufNewFile,BufRead *.todo setlocal foldmethod=indent

" yaml — 2 space indent
au BufNewFile,BufRead *.yml set softtabstop=2 shiftwidth=2
au BufNewFile,BufRead *.yml setlocal foldmethod=indent

" git commits
autocmd Filetype gitcommit setlocal spell textwidth=72

" auto-reload on focus
au FocusGained,BufEnter * :silent! !
au FocusLost,WinLeave * :silent! w

" ############################ plugin config ############################

" go
let g:go_version_warning = 0

" ale
let g:ale_fix_on_save = 1
let g:ale_sign_error = 'E'
let g:ale_sign_warning = 'W'

" coc.nvim
set completeopt=menuone,noinsert,noselect
set shortmess+=c

" tab to trigger completion and navigate
inoremap <silent><expr> <TAB>
      \ coc#pum#visible() ? coc#pum#next(1) :
      \ CheckBackspace() ? "\<Tab>" :
      \ coc#refresh()
inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"

" enter to confirm completion
inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

function! CheckBackspace() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" goto mappings
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" show docs on K
nnoremap <silent> K :call ShowDocumentation()<CR>
function! ShowDocumentation()
  if CocAction('hasProvider', 'hover')
    call CocActionAsync('doHover')
  else
    call feedkeys('K', 'in')
  endif
endfunction

" rename
nmap <leader>rn <Plug>(coc-rename)

" snakecase helper
function! s:snakeize(range) abort
  if a:range == 0
    s#\C\(\<\u[a-z0-9]\+\|[a-z0-9]\+\)\(\u\)#\l\1_\l\2#g
  else
    s#\%V\C\(\<\u[a-z0-9]\+\|[a-z0-9]\+\)\(\u\)\%V#\l\1_\l\2#g
  endif
endfunction

:command  -range Snake silent! call <SID>snakeize(<range>)
